# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        webservice:
            id: AppBundle\Security\User\WebserviceUserProvider
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    encoders:
        AppBundle\Security\User\WebserviceUser: bcrypt
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            switch_user: true
            form_login:
                login_path: login
                check_path: login
             
##           https://symfony.com/doc/current/security/guard_authentication.html 
#            logout: ~
#            guard:
#                authenticators:
#                    - AppBundle\Security\TokenAuthenticator
#
#            # if you want, disable storing the user in the session
#            # stateless: true
#
#            # maybe other things, like form_login, remember_me, etc
#            # ...
            
#            access_control:
#                - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#                - { path: ^/, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            form_login:
#                login_path: login
#                check_path: login
    access_control:
    # require ROLE_ADMIN for /admin*
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/register, roles: ROLE_ADMIN }
    - { path: ^/Tables/users, roles: ROLE_ADMIN }
        